version: "3"
services:
  graphql:
    container_name: graphql
      build: ./server
      restart: unless-stopped
      working_dir: "/go/src/token-svc"
      command: [ "./scripts/build/wait-for-it.sh", "postgres:5432" ]
      ports:
        - "4000:4000"
        - "4001:4001"
      volumes:
        - "./:/go/src/token-svc"
        - "/tmp/certs:/tmp/certs:ro"
        - "/tmp/log:/tmp/log"
  client:
    build:

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - pgvol:/var/lib/postgresql/data
    networks:
      - postgres
    environment:
      POSTGRES_PASSWORD: bulat551

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"

volumes:
  pgvol:
  pgadmin:

networks:
  postgres:
    driver: bridge
